### ISSUE TITLE
how to run this on docker-compose? 

### ISSUE THREAD

**Issue by ghost** [TheKatastrophe/vmail-postfix-dovecot-opendkim#8]
With the docker run command with -it interactive mode I can up the servers. I try to make a docker compose config of it but its not working.

**Comment by lukaszaoralek** [comment]
You can use tty: true, e.g.:

```
version: '3' 

services:
  mail:
    image: katastrophe/vmail-postfix-dovecot-opendkim:latest  
    environment:
      - MAIL_HOSTNAME=mail
      - MAIL_HOSTNAME_FQDN=example.com
    ports:
      - '25:25'
      - '465:465'
      - '587:587'
      - '110:110'  
      - '143:143'  
      - '993:993'  
      - '995:995'  
    hostname: example.com
    tty: true
```
